### ISSUE TITLE
"react-router": "3.0.0" -> "3.2.0"

### ISSUE THREAD

**Issue by iamwill123** [ghoshnirmalya/reddit-clone#1]
Hey, just fyi I noticed I was getting an error after implementing react router @3.0.0, and resolved it by updating to @3.2.0

**Comment by ghoshnirmalya** [comment]
@iamwill123 can you create a PR for that as well?

**Comment by iamwill123** [comment]
@ghoshnirmalya sure thing.

**Comment by ghoshnirmalya** [comment]
Fixed in https://github.com/ghoshnirmalya/reddit-clone/pull/2.
